ALTER TABLE daily_sales_v2
  ADD COLUMN IF NOT EXISTS grab_receipt_count INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS cash_receipt_count INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS qr_receipt_count INTEGER NOT NULL DEFAULT 0;
