import { useEffect, useState } from "react";

const ageMinutes = (createdAt:string) => Math.max(0,Math.floor((Date.now()-new Date(createdAt).getTime())/60000));
const speakReady = (ticket:string) => { if (!("speechSynthesis" in window)) return; window.speechSynthesis.cancel(); const utterance=new SpeechSynthesisUtterance(`Order ${ticket} is ready for collection`); utterance.lang="en-US"; window.speechSynthesis.speak(utterance); };

export default function PosKitchen(){
  const [orders,setOrders]=useState<any[]>([]); const [error,setError]=useState(""); const [,tick]=useState(0);
  const load=()=>fetch('/api/pos/kitchen/orders',{credentials:'include'}).then(r=>r.json()).then(x=>{if(!x.ok)throw Error(x.error);setOrders(x.data||[]);setError("")}).catch(e=>setError(e.message));
  useEffect(()=>{load();const poll=setInterval(load,5000);const clock=setInterval(()=>tick(v=>v+1),30000);return()=>{clearInterval(poll);clearInterval(clock)}},[]);
  const ready=async(id:string,ticket:string)=>{const response=await fetch(`/api/pos/orders/${id}/status`,{method:'PATCH',credentials:'include',headers:{'Content-Type':'application/json'},body:JSON.stringify({status:'ready'})});const body=await response.json();if(!response.ok){setError(body.error||'Could not mark ticket ready');return;}speakReady(ticket);setOrders(current=>current.filter(order=>order.id!==id));};
  return <main className="min-h-dvh bg-neutral-100 p-5"><div className="mb-5"><p className="font-bold text-yellow-600">SBB POS</p><h1 className="text-3xl font-black">Kitchen tickets</h1></div>{error&&<p className="mb-4 rounded bg-red-50 p-3 text-red-700">{error}</p>}<div className="flex items-start gap-3 overflow-x-auto pb-5">{orders.map(o=>{const minutes=ageMinutes(o.created_at);const urgency=minutes>=15?'border-red-600 bg-red-50':minutes>=10?'border-amber-500 bg-amber-50':'border-neutral-300 bg-white';return <article key={o.id} className={`w-[280px] shrink-0 rounded-xl border-2 p-4 shadow-sm ${urgency}`}><div className="flex justify-between"><strong className="text-xl">{o.ticket_number}</strong><span className="rounded bg-yellow-100 px-2 py-1 text-xs font-bold">{o.order_mode}</span></div><p className={`mt-2 text-sm font-black ${minutes>=15?'text-red-700':minutes>=10?'text-amber-700':'text-neutral-600'}`}>{minutes} min · {new Date(o.created_at).toLocaleTimeString([], {hour:'2-digit',minute:'2-digit'})}</p><ul className="my-4 space-y-3">{o.items?.map((i:any)=><li key={i.id}><strong>{i.quantity} × {i.item_name_en}</strong>{i.is_set_component&&<p className="text-sm font-black text-amber-700">SET COMPONENT</p>}{i.modifiers?.map((m:any,index:number)=><p key={index} className="text-sm text-green-700">+ {m.name_en}</p>)}{i.notes&&<p className="mt-1 rounded bg-red-100 px-2 py-1 text-sm font-bold text-red-800">REQUEST: {i.notes}</p>}</li>)}</ul><button className="w-full rounded bg-green-600 p-3 font-bold text-white" onClick={()=>ready(o.id,o.ticket_number)}>Mark ready & call ticket</button></article>})}</div>{!orders.length&&!error&&<p className="rounded border bg-white p-8 text-center text-neutral-500">No active POS tickets.</p>}</main>
}
