import { useEffect, useMemo, useState } from "react";

type MenuItem = { id:string; name_en:string; category_name:string; active_price:number; set_upgrade_eligible:boolean };
type CartLine = MenuItem & { quantity:number; set_upgrade?:boolean; set_drink_menu_item_id?:string };
const baht = (n:number) => `฿${Number(n || 0).toLocaleString()}`;

export default function PosRegister() {
  const [mode,setMode]=useState<"direct"|"grab">("direct"); const [menu,setMenu]=useState<MenuItem[]>([]); const [cart,setCart]=useState<CartLine[]>([]); const [notice,setNotice]=useState("");
  useEffect(()=>{ fetch(`/api/pos/menu?price_mode=${mode}`,{credentials:"include"}).then(r=>r.json()).then(x=>{setMenu(x.data||[]);setCart([])}).catch(()=>setNotice("Could not load POS menu.")); },[mode]);
  const drinks=useMemo(()=>menu.filter(i=>/coke|fanta|schweppes|soda|water/i.test(i.category_name+" "+i.name_en)),[menu]);
  const total=cart.reduce((sum,l)=>sum+(l.active_price+(l.set_upgrade?80:0))*l.quantity,0);
  const add=(item:MenuItem)=>setCart(c=>{const found=c.find(x=>x.id===item.id&&!x.set_upgrade);return found?c.map(x=>x===found?{...x,quantity:x.quantity+1}:x):[...c,{...item,quantity:1}]});
  const submit=async()=>{setNotice("");try { const payload={order_mode:mode,payment_method:mode==="grab"?"grab":"cash",items:cart.map(x=>({menu_item_id:x.id,quantity:x.quantity,set_upgrade:mode==="direct"&&x.set_upgrade,set_drink_menu_item_id:x.set_drink_menu_item_id}))}; const r=await fetch("/api/pos/orders",{method:"POST",credentials:"include",headers:{"Content-Type":"application/json"},body:JSON.stringify(payload)}); const x=await r.json(); if(!r.ok)throw new Error(x.error||"Could not create order");setCart([]);setNotice(`Ticket ${x.data.ticket_number} sent to kitchen`);}catch(e:any){setNotice(e.message)}};
  return <main className="min-h-screen bg-zinc-950 p-4 text-white"><header className="mb-4 flex items-center justify-between"><div><p className="text-xs font-bold tracking-widest text-yellow-400">SMASH BROTHERS</p><h1 className="text-3xl font-black">REGISTER POS</h1></div><div className="rounded-lg bg-zinc-800 p-1"><button className={`rounded px-4 py-2 font-bold ${mode==='direct'?'bg-yellow-400 text-black':''}`} onClick={()=>setMode('direct')}>Direct</button><button className={`rounded px-4 py-2 font-bold ${mode==='grab'?'bg-green-500':''}`} onClick={()=>setMode('grab')}>Grab</button></div></header>{notice&&<div className="mb-3 rounded bg-white p-3 font-semibold text-black">{notice}</div>}<div className="grid gap-4 lg:grid-cols-[1fr_360px]"><section className="grid grid-cols-2 gap-3 md:grid-cols-3 xl:grid-cols-4">{menu.map(item=><button key={item.id} onClick={()=>add(item)} className="min-h-28 rounded-xl border border-zinc-700 bg-zinc-900 p-4 text-left hover:border-yellow-400"><p className="font-bold">{item.name_en}</p><p className="mt-3 text-xl font-black text-yellow-400">{baht(item.active_price)}</p></button>)}</section><aside className="rounded-xl bg-white p-4 text-black"><h2 className="text-xl font-black">Current order</h2>{cart.length===0?<p className="py-8 text-zinc-500">Tap items to begin.</p>:cart.map((line,index)=><div key={`${line.id}-${index}`} className="border-b py-3"><div className="flex justify-between font-semibold"><span>{line.quantity} × {line.name_en}</span><span>{baht((line.active_price+(line.set_upgrade?80:0))*line.quantity)}</span></div>{mode==='direct'&&line.set_upgrade_eligible&&<div className="mt-2"><label className="text-sm"><input type="checkbox" checked={!!line.set_upgrade} onChange={e=>setCart(c=>c.map((x,i)=>i===index?{...x,set_upgrade:e.target.checked,set_drink_menu_item_id:undefined}:x))}/> Make it a set +฿80</label>{line.set_upgrade&&<select className="mt-2 w-full rounded border p-2" value={line.set_drink_menu_item_id||""} onChange={e=>setCart(c=>c.map((x,i)=>i===index?{...x,set_drink_menu_item_id:e.target.value}:x))}><option value="">Select required drink</option>{drinks.map(d=><option key={d.id} value={d.id}>{d.name_en}</option>)}</select>}</div>}</div>)}<div className="mt-4 flex justify-between text-2xl font-black"><span>Total</span><span>{baht(total)}</span></div><button disabled={!cart.length} onClick={submit} className="mt-4 w-full rounded-lg bg-yellow-400 p-4 text-lg font-black text-black disabled:opacity-40">Send to kitchen</button></aside></div></main>;
}
