import { useEffect, useState } from "react";

type Shift = { id:string; register_code:string; status:string; opened_at:string; opened_by_name:string; opening_float:number; cash_sales:number; money_in:number; money_out:number; live_expected_cash:number; expected_cash:number; cash_variance:number|null; receipt_count:number };
type Receipt = { id:string; ticket_number:string; created_at:string; collected_at?:string; status:string; payment_method:string; total:number; discount_name?:string; discount_amount?:number; items:any[] };
const thb=(n:number)=>"฿"+Number(n||0).toLocaleString(undefined,{minimumFractionDigits:2,maximumFractionDigits:2});
const when=(v?:string)=>v?new Date(v).toLocaleString():"—";
const out=[["shopping","Shopping"],["wages","Wages"],["staff_payment","Other staff payments"],["other","Other money out"]];
const incoming=[["owner_funding","Owner funding"],["refund","Refund"],["cash_correction","Cash correction"],["other","Other money in"]];

export default function PosShifts(){
 const [current,setCurrent]=useState<Shift|null>(null),[history,setHistory]=useState<Shift[]>([]),[float,setFloat]=useState(""),[closing,setClosing]=useState(""),[notice,setNotice]=useState(""),[busy,setBusy]=useState(false),[selected,setSelected]=useState<Shift|null>(null),[receipts,setReceipts]=useState<Receipt[]>([]),[moves,setMoves]=useState<any[]>([]);
 const [move,setMove]=useState({direction:"out",category:"shopping",amount:"",note:""});
 const load=async()=>{try{const rs=await Promise.all([fetch("/api/pos/shifts/current",{credentials:"include"}),fetch("/api/pos/shifts/history",{credentials:"include"})]);const a=await rs[0].json(),b=await rs[1].json();if(!a.ok)throw Error(a.error);setCurrent(a.data||null);setHistory(b.data||[])}catch(e:any){setNotice(e.message||"Could not load register shifts")}};
 useEffect(()=>{load()},[]);
 const post=async(path:string,body:any)=>{const r=await fetch(path,{method:"POST",credentials:"include",headers:{"Content-Type":"application/json"},body:JSON.stringify(body)});const b=await r.json();if(!r.ok)throw Error(b.error);return b};
 const open=async()=>{setBusy(true);try{await post("/api/pos/shifts/open",{opening_float:float||0});setFloat("");await load()}catch(e:any){setNotice(e.message)}finally{setBusy(false)}};
 const addMove=async()=>{if(!current)return;setBusy(true);try{await post("/api/pos/shifts/"+current.id+"/movements",move);setMove({direction:"out",category:"shopping",amount:"",note:""});await load();await inspect(current)}catch(e:any){setNotice(e.message)}finally{setBusy(false)}};
 const close=async()=>{if(!current)return;setBusy(true);try{const r=await post("/api/pos/shifts/"+current.id+"/close",{closing_counted_cash:closing||0});setCurrent(null);setSelected(r.data);setClosing("");await load()}catch(e:any){setNotice(e.message)}finally{setBusy(false)}};
 const inspect=async(s:Shift)=>{try{const r=await fetch("/api/pos/shifts/"+s.id+"/receipts",{credentials:"include"}),b=await r.json();if(!r.ok)throw Error(b.error);setSelected(b.data.shift);setReceipts(b.data.receipts||[]);setMoves(b.data.cash_movements||[])}catch(e:any){setNotice(e.message)}};
 const categories=move.direction==="out"?out:incoming;
 return <main className="min-h-dvh bg-zinc-100 p-5"><div className="mx-auto max-w-6xl"><div className="flex flex-wrap items-center justify-between gap-3"><div><p className="font-black tracking-[.16em] text-[#15945c]">SBB POS</p><h1 className="text-3xl font-black">Register shifts & receipts</h1><p className="text-sm text-zinc-500">Every order stays stored and is organised under its active register shift.</p></div><div className="flex gap-2"><a href="/pos/collection" className="rounded-xl bg-zinc-900 px-4 py-3 font-bold text-white">Collection</a><button onClick={()=>window.print()} className="rounded-xl border bg-white px-4 py-3 font-bold">Print</button></div></div>
 {notice&&<button onClick={()=>setNotice("")} className="mt-4 rounded-xl bg-red-50 px-4 py-3 font-bold text-red-700">{notice} · Close</button>}
 {!current?<section className="mt-6 max-w-lg rounded-3xl bg-white p-6 shadow-sm"><h2 className="text-xl font-black">Open register shift</h2><p className="mt-1 text-sm text-zinc-500">Count and enter the opening cash float.</p><label className="mt-5 block text-sm font-bold">Opening float (฿)<input value={float} onChange={e=>setFloat(e.target.value)} inputMode="decimal" placeholder="0.00" className="mt-2 w-full rounded-xl border px-4 py-3"/></label><button disabled={busy} onClick={open} className="mt-4 w-full rounded-xl bg-[#ffd400] px-4 py-3 font-black">Open shift</button></section>:
 <section className="mt-6 grid gap-5 lg:grid-cols-[1.1fr_.9fr]"><div className="rounded-3xl bg-white p-6 shadow-sm"><div className="flex justify-between"><div><p className="text-xs font-black text-[#15945c]">OPEN SHIFT</p><h2 className="text-2xl font-black">Register: {current.register_code}</h2><p className="text-sm text-zinc-500">Opened {when(current.opened_at)} by {current.opened_by_name}</p></div><button onClick={()=>inspect(current)} className="rounded-xl border px-3 py-2 font-bold">Receipts</button></div><div className="mt-5 grid grid-cols-2 gap-3 sm:grid-cols-3">{[["Float",thb(current.opening_float)],["Cash sales",thb(current.cash_sales)],["Money in",thb(current.money_in)],["Money out",thb(-current.money_out)],["Expected cash",thb(current.live_expected_cash)],["Receipts",current.receipt_count]].map(x=><div key={x[0]} className="rounded-2xl bg-zinc-50 p-3"><p className="text-xs font-bold text-zinc-500">{x[0]}</p><p className="mt-1 text-lg font-black">{x[1]}</p></div>)}</div></div>
 <div className="rounded-3xl bg-white p-6 shadow-sm"><h2 className="text-xl font-black">Cash movements</h2><div className="mt-4 grid gap-3"><select value={move.direction} onChange={e=>setMove({direction:e.target.value,category:e.target.value==="out"?"shopping":"owner_funding",amount:"",note:""})} className="rounded-xl border px-3 py-3"><option value="out">Money out</option><option value="in">Money in</option></select><select value={move.category} onChange={e=>setMove({...move,category:e.target.value})} className="rounded-xl border px-3 py-3">{categories.map(x=><option key={x[0]} value={x[0]}>{x[1]}</option>)}</select><input value={move.amount} onChange={e=>setMove({...move,amount:e.target.value})} inputMode="decimal" placeholder="Amount (฿)" className="rounded-xl border px-3 py-3"/><input value={move.note} onChange={e=>setMove({...move,note:e.target.value})} placeholder="Reason / description" className="rounded-xl border px-3 py-3"/><button disabled={busy} onClick={addMove} className="rounded-xl bg-zinc-900 px-4 py-3 font-black text-white">Record movement</button></div><div className="mt-6 border-t pt-5"><label className="text-sm font-bold">Closing counted cash (฿)<input value={closing} onChange={e=>setClosing(e.target.value)} inputMode="decimal" placeholder={String(current.live_expected_cash)} className="mt-2 w-full rounded-xl border px-3 py-3"/></label><button disabled={busy} onClick={close} className="mt-3 w-full rounded-xl bg-red-600 px-4 py-3 font-black text-white">Close shift & record variance</button></div></div></section>}
 <section className="mt-7 rounded-3xl bg-white p-6 shadow-sm"><h2 className="text-xl font-black">Shift history</h2><div className="mt-4 overflow-x-auto"><table className="w-full text-left text-sm"><thead><tr className="border-b text-zinc-500"><th className="p-2">Opened</th><th className="p-2">Cashier</th><th className="p-2">Status</th><th className="p-2">Receipts</th><th className="p-2">Expected cash</th><th className="p-2"></th></tr></thead><tbody>{history.map(s=><tr className="border-b" key={s.id}><td className="p-2">{when(s.opened_at)}</td><td className="p-2">{s.opened_by_name}</td><td className="p-2 font-bold">{s.status}</td><td className="p-2">{s.receipt_count}</td><td className="p-2">{thb(s.status==="closed"?s.expected_cash:s.live_expected_cash)}</td><td className="p-2"><button onClick={()=>inspect(s)} className="font-bold text-[#15945c]">Receipts</button></td></tr>)}</tbody></table></div></section>
 {selected&&<section className="mt-7 rounded-3xl bg-white p-6 shadow-sm"><div className="flex justify-between"><div><p className="text-xs font-black text-[#15945c]">PRINTABLE SHIFT RECEIPT REGISTER</p><h2 className="text-2xl font-black">{when(selected.opened_at)} · {selected.status}</h2><p className="text-sm text-zinc-500">{selected.opened_by_name} · float {thb(selected.opening_float)}</p></div><button onClick={()=>setSelected(null)}>Close</button></div><p className="mt-3 text-sm font-bold">Cash movements: {moves.length}</p><div className="mt-5 space-y-3">{receipts.map(r=><article key={r.id} className="break-inside-avoid rounded-2xl border p-4"><div className="flex justify-between"><div><strong>{r.ticket_number}</strong><p className="text-xs text-zinc-500">{when(r.created_at)} · {r.payment_method} · {r.status}</p></div><strong>{thb(r.total)}</strong></div><ul className="mt-3 border-t pt-3 text-sm">{r.items.filter(i=>!i.is_set_component).map(i=><li key={i.id} className="flex justify-between py-1"><span>{i.quantity} × {i.name}{i.modifiers?.map((m:any)=>" + "+m.name).join("")}{i.notes?" — "+i.notes:""}</span><span>{thb(i.line_total)}</span></li>)}</ul>{r.discount_name&&<p className="mt-2 text-sm font-bold text-[#15945c]">{r.discount_name} −{thb(r.discount_amount)}</p>}</article>)}</div></section>}
 </div></main>;
}