ALTER TABLE recipes
  ADD COLUMN IF NOT EXISTS service_minutes NUMERIC(10,2) NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS prep_allocation_minutes NUMERIC(10,2) NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS packaging_minutes NUMERIC(10,2) NOT NULL DEFAULT 0;
