import { useMemo, useState } from "react";
import { useQuery } from "@tanstack/react-query";
import { PageTitle } from "@/components/ui/sbb-cards";

type Item={name:string;sku:string;category:string;qtySold:number;grossSales:number;discounts:number;netSales:number;avgPrice:number;baseRevenue:number};
type Component={type:"Modifier"|"Option"|"Upsell";group:string;name:string;qtySold:number;revenue:number};
type Included={name:string;category:string;qtySold:number};
type Data={ok:boolean;itemSales:Item[];componentSales:Component[];includedComponents:Included[];summary:{grossSales:number;receiptCount:number};filters:{windowStart:string;windowEnd:string;timezone:string};blockers?:{message:string}[]};
const money=(v:number)=>`฿${Number(v||0).toLocaleString("en-US",{maximumFractionDigits:2})}`;
const today=()=>new Intl.DateTimeFormat("en-CA",{timeZone:"Asia/Bangkok",year:"numeric",month:"2-digit",day:"2-digit"}).format(new Date());
const yesterday=()=>{const d=new Date();d.setDate(d.getDate()-1);return new Intl.DateTimeFormat("en-CA",{timeZone:"Asia/Bangkok",year:"numeric",month:"2-digit",day:"2-digit"}).format(d)};

export default function SalesByItem(){
  const [fromDate,setFromDate]=useState(yesterday()); const [fromTime,setFromTime]=useState("17:00"); const [toDate,setToDate]=useState(today()); const [toTime,setToTime]=useState("03:00"); const [search,setSearch]=useState("");
  const params=useMemo(()=>new URLSearchParams({fromDate,fromTime,toDate,toTime}).toString(),[fromDate,fromTime,toDate,toTime]);
  const {data,isLoading,isError}=useQuery<Data>({queryKey:["sales-by-item-v2",params],queryFn:async()=>{const r=await fetch(`/api/reports/receipt-analytics?${params}`,{credentials:"include",cache:"no-store"});if(!r.ok)throw new Error(`HTTP ${r.status}`);return r.json()}});
  const q=search.trim().toLowerCase(); const items=(data?.itemSales||[]).filter(x=>!q||x.name.toLowerCase().includes(q)||x.category.toLowerCase().includes(q)); const comps=(data?.componentSales||[]).filter(x=>!q||x.name.toLowerCase().includes(q)||x.group.toLowerCase().includes(q)||x.type.toLowerCase().includes(q)); const included=(data?.includedComponents||[]).filter(x=>!q||x.name.toLowerCase().includes(q));
  const itemQty=items.reduce((a,x)=>a+x.qtySold,0); const modRevenue=comps.reduce((a,x)=>a+x.revenue,0);
  return <div className="mx-auto max-w-7xl space-y-5">
    <PageTitle title="Sales by Item" meta="POS items, options, modifiers, upsells and included components · no double counting" />
    <div className="rounded-2xl border border-slate-200 bg-white p-4 shadow-sm"><div className="grid gap-3 md:grid-cols-4"><label className="text-xs font-bold">From date<input type="date" value={fromDate} onChange={e=>setFromDate(e.target.value)} className="mt-1 w-full rounded-xl border px-3 py-2"/></label><label className="text-xs font-bold">From time<input type="time" value={fromTime} onChange={e=>setFromTime(e.target.value)} className="mt-1 w-full rounded-xl border px-3 py-2"/></label><label className="text-xs font-bold">To date<input type="date" value={toDate} onChange={e=>setToDate(e.target.value)} className="mt-1 w-full rounded-xl border px-3 py-2"/></label><label className="text-xs font-bold">To time<input type="time" value={toTime} onChange={e=>setToTime(e.target.value)} className="mt-1 w-full rounded-xl border px-3 py-2"/></label></div><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search item, modifier or upsell…" className="mt-4 w-full max-w-md rounded-xl border px-3 py-2 text-sm"/></div>
    <div className="rounded-xl border border-blue-200 bg-blue-50 px-4 py-3 text-xs text-blue-900"><b>Counting rule:</b> each commercial product is counted once. Every selected option/modifier/upsell is classified once in the second table. Included set components such as fries and drinks are tracked separately for stock/ingredient usage and carry no additional sales revenue here.</div>
    <div className="grid grid-cols-2 gap-3 md:grid-cols-4"><div className="rounded-xl border bg-white p-4"><p className="text-[10px] font-bold uppercase text-slate-500">Receipts</p><p className="text-xl font-black">{data?.summary?.receiptCount||0}</p></div><div className="rounded-xl border bg-white p-4"><p className="text-[10px] font-bold uppercase text-slate-500">Units sold</p><p className="text-xl font-black">{itemQty}</p></div><div className="rounded-xl border bg-white p-4"><p className="text-[10px] font-bold uppercase text-slate-500">Receipt sales</p><p className="text-xl font-black">{money(data?.summary?.grossSales||0)}</p></div><div className="rounded-xl border bg-white p-4"><p className="text-[10px] font-bold uppercase text-slate-500">Modifier/Upsell value</p><p className="text-xl font-black">{money(modRevenue)}</p><p className="text-[10px] text-slate-400">Already included in receipt sales</p></div></div>
    {isLoading&&<div className="rounded-2xl border bg-white p-8 text-center text-sm text-slate-500">Loading POS sales…</div>}{isError&&<div className="rounded-2xl border border-red-200 bg-red-50 p-4 text-red-700">Could not load item sales.</div>}
    {!isLoading&&!isError&&<>
      <section className="overflow-hidden rounded-2xl border bg-white shadow-sm"><div className="border-b px-4 py-3"><h2 className="font-black">Items Sold</h2><p className="text-xs text-slate-500">One row per commercial menu item.</p></div><div className="overflow-x-auto"><table className="w-full min-w-[850px] text-sm"><thead className="bg-slate-50 text-[11px] uppercase text-slate-500"><tr><th className="px-4 py-3 text-left">Item</th><th className="px-4 py-3 text-left">Category</th><th className="px-4 py-3 text-right">Qty</th><th className="px-4 py-3 text-right">Gross</th><th className="px-4 py-3 text-right">Discount</th><th className="px-4 py-3 text-right">Net</th></tr></thead><tbody className="divide-y">{items.map(x=><tr key={`${x.sku}-${x.name}`}><td className="px-4 py-3 font-bold">{x.name}</td><td className="px-4 py-3">{x.category}</td><td className="px-4 py-3 text-right font-bold">{x.qtySold}</td><td className="px-4 py-3 text-right">{money(x.grossSales)}</td><td className="px-4 py-3 text-right">{money(x.discounts)}</td><td className="px-4 py-3 text-right font-black">{money(x.netSales)}</td></tr>)}</tbody></table></div></section>
      <section className="overflow-hidden rounded-2xl border bg-white shadow-sm"><div className="border-b px-4 py-3"><h2 className="font-black">Options, Modifiers & Upsells</h2><p className="text-xs text-slate-500">Every stored selection appears once and only once.</p></div><div className="overflow-x-auto"><table className="w-full min-w-[700px] text-sm"><thead className="bg-slate-50 text-[11px] uppercase text-slate-500"><tr><th className="px-4 py-3 text-left">Type</th><th className="px-4 py-3 text-left">Group</th><th className="px-4 py-3 text-left">Selection</th><th className="px-4 py-3 text-right">Qty</th><th className="px-4 py-3 text-right">Value</th></tr></thead><tbody className="divide-y">{comps.map((x,i)=><tr key={`${x.type}-${x.group}-${x.name}-${i}`}><td className="px-4 py-3"><span className={`rounded-full px-2 py-1 text-[10px] font-bold ${x.type==="Upsell"?"bg-amber-100 text-amber-800":x.type==="Option"?"bg-blue-100 text-blue-800":"bg-slate-100 text-slate-700"}`}>{x.type}</span></td><td className="px-4 py-3">{x.group}</td><td className="px-4 py-3 font-bold">{x.name}</td><td className="px-4 py-3 text-right font-bold">{x.qtySold}</td><td className="px-4 py-3 text-right">{money(x.revenue)}</td></tr>)}</tbody></table></div></section>
      <section className="overflow-hidden rounded-2xl border bg-white shadow-sm"><div className="border-b px-4 py-3"><h2 className="font-black">Included Components</h2><p className="text-xs text-slate-500">For ingredient/stock usage: set fries, selected drinks and other zero-additional-revenue components.</p></div><div className="overflow-x-auto"><table className="w-full min-w-[550px] text-sm"><thead className="bg-slate-50 text-[11px] uppercase text-slate-500"><tr><th className="px-4 py-3 text-left">Component</th><th className="px-4 py-3 text-left">Category</th><th className="px-4 py-3 text-right">Qty Used</th></tr></thead><tbody className="divide-y">{included.map(x=><tr key={`${x.category}-${x.name}`}><td className="px-4 py-3 font-bold">{x.name}</td><td className="px-4 py-3">{x.category}</td><td className="px-4 py-3 text-right font-black">{x.qtySold}</td></tr>)}</tbody></table></div></section>
    </>}
  </div>
}
