import { useState } from "react";
import { useMutation, useQuery } from "@tanstack/react-query";
import { Input } from "@/components/ui/input";
import { apiRequest, queryClient } from "@/lib/queryClient";
import { asArray, normalizeMenuCategories } from "@/lib/menuData";
import { toNumber, type MenuCategory } from "./recipeTypes";

export default function MenuCategoriesPage() {
  const [form, setForm] = useState({ id: "", name: "", sortOrder: "" });
  const { data: rawCategories, isLoading } = useQuery<unknown>({ queryKey: ["/api/menu-v3/categories"] });
  const categories = asArray<MenuCategory>(normalizeMenuCategories<MenuCategory>(rawCategories).items);
  const reset = () => setForm({ id: "", name: "", sortOrder: "" });
  const createMutation = useMutation({ mutationFn: () => apiRequest("/api/menu-v3/categories/create", { method: "POST", body: JSON.stringify({ name: form.name, sortOrder: toNumber(form.sortOrder) ?? 0, isActive: true }) }), onSuccess: () => { queryClient.invalidateQueries({ queryKey: ["/api/menu-v3/categories"] }); reset(); } });
  const updateMutation = useMutation({ mutationFn: () => apiRequest("/api/menu-v3/categories/update", { method: "POST", body: JSON.stringify({ id: form.id, name: form.name, sortOrder: toNumber(form.sortOrder) ?? 0, isActive: true }) }), onSuccess: () => { queryClient.invalidateQueries({ queryKey: ["/api/menu-v3/categories"] }); reset(); } });
  const deleteMutation = useMutation({ mutationFn: (id: string) => apiRequest("/api/menu-v3/categories/delete", { method: "POST", body: JSON.stringify({ id }) }), onSuccess: () => queryClient.invalidateQueries({ queryKey: ["/api/menu-v3/categories"] }) });
  return <div className="space-y-3"><p className="text-xs text-slate-500">Menu category management. Categories created here are available immediately in the recipe category dropdown.</p><div className="border rounded-lg bg-white p-3 space-y-2"><p className="text-xs font-semibold">{form.id ? "Edit category" : "Add category"}</p><div className="grid grid-cols-1 md:grid-cols-[1fr_160px_auto_auto] gap-2"><Input placeholder="Category name" value={form.name} onChange={(event) => setForm({ ...form, name: event.target.value })} /><Input placeholder="Display order" value={form.sortOrder} onChange={(event) => setForm({ ...form, sortOrder: event.target.value })} /><button onClick={() => form.id ? updateMutation.mutate() : createMutation.mutate()} disabled={!form.name} className="text-xs px-3 py-1.5 bg-black text-white rounded-lg disabled:opacity-40">{form.id ? "Save" : "Add Category"}</button>{form.id && <button onClick={reset} className="text-xs px-3 py-1.5 border rounded-lg">Cancel</button>}</div></div><div className="border rounded-lg overflow-x-auto bg-white"><table className="w-full min-w-[700px] text-xs"><thead><tr className="border-b bg-slate-50"><th className="text-left p-2">Name</th><th className="text-left p-2">Display order</th><th className="text-left p-2">Active status</th><th className="text-left p-2">Online visibility</th><th className="text-left p-2">Actions</th></tr></thead><tbody>{isLoading ? <tr><td className="p-3" colSpan={5}>Loading categories...</td></tr> : categories.map((category) => <tr key={category.id} className="border-b"><td className="p-2 font-medium">{category.name}</td><td className="p-2 font-mono">{category.sortOrder ?? category.displayOrder ?? "UNMAPPED"}</td><td className="p-2">{category.isActive === false ? "Inactive" : "Active"}</td><td className="p-2">Online: {(category.onlineEnabled ?? category.visibleOnline) ? "Yes" : "No"}</td><td className="p-2"><div className="flex gap-2"><button onClick={() => setForm({ id: category.id, name: category.name, sortOrder: String(category.sortOrder ?? category.displayOrder ?? "") })} className="text-xs px-2 py-1 border rounded">Edit</button><button onClick={() => deleteMutation.mutate(category.id)} disabled={category.isActive === false} className="text-xs px-2 py-1 border border-red-300 text-red-700 rounded disabled:opacity-40">Delete</button></div></td></tr>)}</tbody></table></div></div>;
}
