import { useMemo, useState } from "react";
import { Trash2 } from "lucide-react";
import { fmtMoney, makeIngredient, recipeIngredientCost, type Recipe, type RecipeIngredientRow } from "./recipeTypes";

type Props={rows:RecipeIngredientRow[];recipes:Recipe[];currentRecipeId?:number|null;onRowsChange:(rows:RecipeIngredientRow[])=>void};

export default function RecipeComponentEditor({rows,recipes,currentRecipeId,onRowsChange}:Props){
 const [recipeId,setRecipeId]=useState(""); const [qty,setQty]=useState("1");
 const available=useMemo(()=>recipes.filter(r=>r.id!==currentRecipeId&&r.isActive===true&&Number.isFinite(Number(r.costPerServing))),[recipes,currentRecipeId]);
 const add=()=>{const recipe=available.find(r=>r.id===Number(recipeId));const quantity=Number(qty);if(!recipe||!Number.isFinite(quantity)||quantity<=0)return;const row:RecipeIngredientRow={...makeIngredient("component"),lineType:"component",sourceType:"recipe",recipeId:recipe.id,name:recipe.name,purchaseCost:String(recipe.costPerServing??""),packageQuantity:"1",purchaseUnit:"each",quantityUsed:String(quantity),unitUsed:"each",wastePercent:"",costingStatus:"CURRENT_RECIPE_COST",notes:"Composed recipe component"};onRowsChange([...rows,row]);setRecipeId("");setQty("1");};
 return <section className="space-y-3 rounded-lg border bg-white p-4">
  <div><h2 className="text-sm font-semibold">Composed Recipe Components</h2><p className="mt-1 text-xs text-slate-500">Build sets and meal deals from approved recipes. Component cost uses the child recipe's current cost per serving and automatically cascades when that recipe changes.</p></div>
  <div className="grid grid-cols-1 gap-2 md:grid-cols-[1fr_120px_auto]"><select value={recipeId} onChange={e=>setRecipeId(e.target.value)} className="rounded border px-2 py-2 text-xs"><option value="">Select approved recipe component</option>{available.map(r=><option key={r.id} value={r.id}>{r.name} · {fmtMoney(r.costPerServing)} / serving</option>)}</select><input type="number" min="0.01" step="any" value={qty} onChange={e=>setQty(e.target.value)} className="rounded border px-2 py-2 text-xs" aria-label="Component quantity"/><button type="button" onClick={add} disabled={!recipeId||Number(qty)<=0} className="rounded-lg bg-black px-3 py-2 text-xs text-white disabled:opacity-40">Add component</button></div>
  <div className="overflow-x-auto rounded-lg border"><table className="w-full min-w-[650px] text-xs"><thead><tr className="border-b bg-slate-50"><th className="p-2 text-left">Component recipe</th><th className="p-2 text-right">Qty</th><th className="p-2 text-right">Cost / serving</th><th className="p-2 text-right">Line cost</th><th className="p-2 text-left">Action</th></tr></thead><tbody>{rows.length===0?<tr><td colSpan={5} className="p-3">No composed recipe components added.</td></tr>:rows.map(row=>{const cost=recipeIngredientCost(row);return <tr key={row.id} className="border-b"><td className="p-2 font-medium">{row.name}</td><td className="p-2 text-right">{row.quantityUsed}</td><td className="p-2 text-right">{fmtMoney(row.purchaseCost)}</td><td className="p-2 text-right font-mono">{fmtMoney(cost.lineCost)}</td><td className="p-2"><button type="button" title={`Remove ${row.name}`} className="rounded p-1 text-red-700 hover:bg-red-50" onClick={()=>onRowsChange(rows.filter(x=>x.id!==row.id))}><Trash2 className="h-4 w-4"/></button></td></tr>})}</tbody></table></div>
 </section>;
}