import { useEffect, useMemo, useState } from "react";
import { Link, useLocation, useNavigate, useParams, useSearchParams } from "react-router-dom";
import { useMutation, useQuery } from "@tanstack/react-query";
import { Badge } from "@/components/ui/badge";
import { Input } from "@/components/ui/input";
import { apiRequest, queryClient } from "@/lib/queryClient";
import { asArray, normalizeMenuCategories } from "@/lib/menuData";
import RecipeIngredientEditor from "./RecipeIngredientEditor";
import RecipeComponentEditor from "./RecipeComponentEditor";
import { COSTING_NOTES_PREFIX, createClientId, emptyRecipeForm, fmtMoney, fmtPercent, notesWithoutWorkflowData, parseCostingRows, parseStatus, recipeIngredientCost, splitInstructions, toNumber, type MenuCategory, type Recipe, type RecipeIngredientRow } from "./recipeTypes";

function blockerText(message: string) { return <div className="rounded-lg border border-amber-200 bg-amber-50 p-3 text-xs text-amber-800"><p className="font-semibold">INSUFFICIENT DATA</p><p>{message}</p></div>; }

export default function RecipeEditorPage() {
  const navigate = useNavigate(); const location = useLocation(); const { recipeId } = useParams<{ recipeId?: string }>(); const [searchParams] = useSearchParams();
  const isNewRecipe = recipeId === "new" || location.pathname === "/menu/recipes/new";
  const [form, setForm] = useState(emptyRecipeForm()); const [ingredients, setIngredients] = useState<RecipeIngredientRow[]>([]); const [packagingCosts, setPackagingCosts] = useState<RecipeIngredientRow[]>([]); const [components,setComponents]=useState<RecipeIngredientRow[]>([]); const [draftIngredient, setDraftIngredient] = useState<RecipeIngredientRow | null>(null); const [draftPackaging, setDraftPackaging] = useState<RecipeIngredientRow | null>(null);
  const { data: recipesData, isLoading: recipesLoading } = useQuery<Recipe[] | { rows?: Recipe[] }>({ queryKey: ["/api/recipes"] }); const { data: rawCategories } = useQuery<unknown>({ queryKey: ["/api/menu-v3/categories"] });
  const categories = asArray<MenuCategory>(normalizeMenuCategories<MenuCategory>(rawCategories).items).filter((category) => category.isActive !== false); const recipes = Array.isArray(recipesData) ? recipesData : asArray<Recipe>(recipesData?.rows); const recipe = isNewRecipe ? null : recipes.find((candidate) => String(candidate.id) === recipeId) ?? null; const cloneSource = isNewRecipe ? recipes.find((candidate) => String(candidate.id) === searchParams.get("cloneFrom")) ?? null : null;

  useEffect(() => {
    if (isNewRecipe) {
      if (cloneSource) { const split=splitInstructions(cloneSource.instructions); setForm({name:`Copy of ${cloneSource.name??"Recipe"}`,category:cloneSource.category??"",description:cloneSource.description??"",imageUrl:cloneSource.imageUrl??"",yieldQuantity:String(cloneSource.yieldQuantity??"1"),yieldUnit:cloneSource.yieldUnit??"servings",preparationInstructions:split.preparationInstructions,cookingInstructions:split.cookingInstructions,specialNotes:notesWithoutWorkflowData(cloneSource.notes),directPrice:cloneSource.sellingPrice==null?"":String(cloneSource.sellingPrice),deliveryPartnerPrice:cloneSource.suggestedPrice==null?"":String(cloneSource.suggestedPrice),status:"Draft"}); const rows=parseCostingRows(cloneSource).map(row=>({...row,id:createClientId(row.lineType)}));setIngredients(rows.filter(row=>row.lineType==="ingredient"));setPackagingCosts(rows.filter(row=>row.lineType==="packaging"));setComponents(rows.filter(row=>row.lineType==="component"||row.sourceType==="recipe"));setDraftIngredient(null);setDraftPackaging(null); }
      else { setForm(emptyRecipeForm());setIngredients([]);setPackagingCosts([]);setComponents([]); }
      return;
    }
    if(!recipe)return; const split=splitInstructions(recipe.instructions);setForm({name:recipe.name??"",category:recipe.category??"",description:recipe.description??"",imageUrl:recipe.imageUrl??"",yieldQuantity:String(recipe.yieldQuantity??"1"),yieldUnit:recipe.yieldUnit??"servings",preparationInstructions:split.preparationInstructions,cookingInstructions:split.cookingInstructions,specialNotes:notesWithoutWorkflowData(recipe.notes),directPrice:recipe.sellingPrice==null?"":String(recipe.sellingPrice),deliveryPartnerPrice:recipe.suggestedPrice==null?"":String(recipe.suggestedPrice),status:parseStatus(recipe)});const rows=parseCostingRows(recipe);setIngredients(rows.filter(row=>row.lineType==="ingredient"));setPackagingCosts(rows.filter(row=>row.lineType==="packaging"));setComponents(rows.filter(row=>row.lineType==="component"||row.sourceType==="recipe"));
  },[isNewRecipe,recipe?.id,cloneSource?.id]);

  const allCostingRows=useMemo(()=>[...ingredients,...components,...packagingCosts],[ingredients,components,packagingCosts]); const costRows=useMemo(()=>allCostingRows.map(row=>({row,...recipeIngredientCost(row)})),[allCostingRows]); const validRows=costRows.filter(entry=>entry.row.name.trim()&&entry.lineCost!==null);const missingRows=costRows.filter(entry=>entry.row.name.trim()&&entry.lineCost===null);const hasValidCostData=validRows.length>0&&missingRows.length===0;const totalCost=hasValidCostData?validRows.reduce((sum,e)=>sum+(e.lineCost??0),0):null;const totalWasteCost=hasValidCostData?validRows.reduce((sum,e)=>sum+(e.wasteCost??0),0):null;const totalWastePercent=totalCost!==null&&totalWasteCost!==null&&totalCost>0?(totalWasteCost/totalCost)*100:null;const ingredientCost=hasValidCostData?costRows.filter(e=>e.row.lineType==="ingredient").reduce((sum,e)=>sum+(e.lineCost??0),0):null;const componentCost=hasValidCostData?costRows.filter(e=>e.row.lineType==="component"||e.row.sourceType==="recipe").reduce((sum,e)=>sum+(e.lineCost??0),0):null;const packagingCost=hasValidCostData?costRows.filter(e=>e.row.lineType==="packaging").reduce((sum,e)=>sum+(e.lineCost??0),0):null;
  const yieldQty=toNumber(form.yieldQuantity);const costPerServing=totalCost!==null&&yieldQty!==null&&yieldQty>0?totalCost/yieldQty:null;const directPrice=toNumber(form.directPrice);const deliveryPartnerPrice=toNumber(form.deliveryPartnerPrice);const directMargin=directPrice!==null&&directPrice>0&&costPerServing!==null?((directPrice-costPerServing)/directPrice)*100:null;const deliveryPartnerMargin=deliveryPartnerPrice!==null&&deliveryPartnerPrice>0&&costPerServing!==null?((deliveryPartnerPrice-costPerServing)/deliveryPartnerPrice)*100:null;const directProfit=directPrice!==null&&costPerServing!==null?directPrice-costPerServing:null;const deliveryPartnerProfit=deliveryPartnerPrice!==null&&costPerServing!==null?deliveryPartnerPrice-costPerServing:null;const suggestedPrice=costPerServing!==null?Math.ceil(costPerServing/0.3):null;

  const saveMutation=useMutation({mutationFn:()=>apiRequest(isNewRecipe?"/api/recipes":`/api/recipes/${recipe!.id}`,{method:isNewRecipe?"POST":"PUT",body:JSON.stringify({name:form.name,category:form.category,description:form.description||null,imageUrl:form.imageUrl||null,yieldQuantity:form.yieldQuantity,yieldUnit:form.yieldUnit,sellingPrice:directPrice,suggestedPrice:deliveryPartnerPrice,totalCost,costPerServing,status:form.status,isActive:form.status==="Approved",instructions:`Preparation instructions:\n${form.preparationInstructions}\n\nCooking/build instructions:\n${form.cookingInstructions}`,notes:`${form.specialNotes?`${form.specialNotes}\n`:""}${COSTING_NOTES_PREFIX} ${JSON.stringify(allCostingRows.map(({id,...row})=>row))}\nRecipe status: ${form.status}`,recipeIngredients:allCostingRows})}),onSuccess:()=>{queryClient.invalidateQueries({queryKey:["/api/recipes"]});navigate("/menu/recipes");}});

  if(!isNewRecipe&&recipesLoading)return <div className="p-4 text-xs text-slate-500">Loading recipe...</div>; if(!isNewRecipe&&!recipe)return <div className="space-y-3 p-4"><Link to="/menu/recipes" className="text-xs underline">Back to Recipes</Link>{blockerText("Recipe could not be loaded from /api/recipes.")}</div>;
  return <div className="mx-auto max-w-5xl space-y-4 p-4">
    <div className="flex flex-col gap-3 md:flex-row md:items-center md:justify-between"><div><Link to="/menu/recipes" className="text-xs underline">Back to Recipes</Link><h1 className="text-xl font-semibold">{isNewRecipe?(cloneSource?`Clone: ${cloneSource.name}`:"Add New Recipe"):recipe!.name}</h1><Badge variant={form.status==="Approved"?"default":"outline"}>{form.status}</Badge></div><button onClick={()=>saveMutation.mutate()} disabled={!form.name||!form.category||saveMutation.isPending} className="rounded-lg bg-black px-4 py-2 text-xs text-white disabled:opacity-40">{saveMutation.isPending?"Saving...":"Save Recipe"}</button></div>
    {saveMutation.error&&blockerText(saveMutation.error instanceof Error?saveMutation.error.message:"Recipe could not be saved.")}
    <section className="space-y-3 rounded-lg border bg-white p-4"><div><h2 className="text-sm font-semibold">Recipe Details</h2><p className="mt-1 text-xs text-slate-500">Recipes hold costing and kitchen instructions. They never publish or change a POS product; link an approved recipe from its Menu Item.</p></div><div className="grid grid-cols-1 gap-3 md:grid-cols-2"><Input placeholder="Recipe title" value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/><select value={form.category} onChange={e=>setForm({...form,category:e.target.value})} className="rounded border px-2 py-2 text-xs"><option value="">Menu category</option>{categories.map(c=><option key={c.id} value={c.name}>{c.name}</option>)}</select><Input placeholder="Description" value={form.description} onChange={e=>setForm({...form,description:e.target.value})} className="md:col-span-2"/><input type="file" accept="image/png,image/jpeg,image/webp" onChange={async e=>{const file=e.target.files?.[0];if(!file)return;const data=new FormData();data.append("image",file);const res=await fetch("/api/upload/menu-item-image",{method:"POST",body:data});const uploaded=await res.json();if(!res.ok)throw new Error(uploaded?.error||"Image upload failed");setForm({...form,imageUrl:uploaded.imageUrl||uploaded.url});}} className="w-full rounded-md border border-slate-200 px-3 py-2 text-xs file:mr-3 file:rounded file:border-0 file:bg-slate-100 file:px-2 file:py-1 file:text-xs md:col-span-2"/><label className="block text-xs font-medium">Yield quantity<Input type="number" min="0.01" step="any" value={form.yieldQuantity} onChange={e=>setForm({...form,yieldQuantity:e.target.value})} className="mt-1"/></label><label className="block text-xs font-medium">Yield unit<Input value={form.yieldUnit} onChange={e=>setForm({...form,yieldUnit:e.target.value})} className="mt-1"/></label><select value={form.status} onChange={e=>setForm({...form,status:e.target.value as typeof form.status})} className="rounded border px-2 py-2 text-xs"><option>Draft</option><option>Tested</option><option>Approved</option><option>Archived</option></select></div><div className="flex h-36 w-36 items-center justify-center overflow-hidden rounded-lg border bg-slate-100 text-xs text-slate-500">{form.imageUrl?<img src={form.imageUrl} alt={form.name} className="h-full w-full object-cover"/>:"No image"}</div></section>
    <section className="space-y-3 rounded-lg border bg-white p-4"><h2 className="text-sm font-semibold">Development Price References</h2><p className="text-xs text-slate-500">Used to test margins while costing a recipe. Live Direct/POS and Partner prices belong to the linked Menu Item and are never changed here.</p><div className="grid grid-cols-1 gap-3 md:grid-cols-2"><label className="block text-xs font-medium">Direct / in-store price<Input value={form.directPrice} onChange={e=>setForm({...form,directPrice:e.target.value})} className="mt-1"/></label><label className="block text-xs font-medium">Delivery partner price<Input value={form.deliveryPartnerPrice} onChange={e=>setForm({...form,deliveryPartnerPrice:e.target.value})} className="mt-1"/></label></div></section>
    <RecipeIngredientEditor rows={ingredients} draft={draftIngredient} onDraftChange={setDraftIngredient} onRowsChange={setIngredients}/>
    <RecipeComponentEditor rows={components} recipes={recipes} currentRecipeId={recipe?.id??null} onRowsChange={setComponents}/>
    <RecipeIngredientEditor rows={packagingCosts} draft={draftPackaging} onDraftChange={setDraftPackaging} onRowsChange={setPackagingCosts} lineType="packaging"/>
    {missingRows.length>0&&blockerText(`${missingRows.length} costing row(s) need a valid ingredient purchase cost or approved component recipe cost.`)}
    <section className="space-y-3 rounded-lg border bg-white p-4"><h2 className="text-sm font-semibold">Instructions</h2><textarea placeholder="Preparation instructions" value={form.preparationInstructions} onChange={e=>setForm({...form,preparationInstructions:e.target.value})} className="min-h-24 w-full rounded-md border px-3 py-2 text-sm"/><textarea placeholder="Cooking/build instructions" value={form.cookingInstructions} onChange={e=>setForm({...form,cookingInstructions:e.target.value})} className="min-h-24 w-full rounded-md border px-3 py-2 text-sm"/><textarea placeholder="Special notes" value={form.specialNotes} onChange={e=>setForm({...form,specialNotes:e.target.value})} className="min-h-20 w-full rounded-md border px-3 py-2 text-sm"/></section>
    <section className="space-y-3 rounded-lg border bg-white p-4"><h2 className="text-sm font-semibold">Cost Summary</h2>{hasValidCostData?<div className="grid grid-cols-1 gap-2 text-xs sm:grid-cols-2 lg:grid-cols-4"><div>Ingredient cost: <span className="font-mono">{fmtMoney(ingredientCost)}</span></div><div>Component recipe cost: <span className="font-mono">{fmtMoney(componentCost)}</span></div><div>Packaging cost: <span className="font-mono">{fmtMoney(packagingCost)}</span></div><div>Total recipe cost: <span className="font-mono">{fmtMoney(totalCost)}</span></div><div>Combined waste: <span className="font-mono">{fmtMoney(totalWasteCost)} · {fmtPercent(totalWastePercent)}</span></div><div>Cost per serving: <span className="font-mono">{fmtMoney(costPerServing)}</span></div><div>Direct margin %: <span className="font-mono">{fmtPercent(directMargin)}</span></div><div>Delivery partner margin %: <span className="font-mono">{fmtPercent(deliveryPartnerMargin)}</span></div><div>Direct profit: <span className="font-mono">{fmtMoney(directProfit)}</span></div><div>Delivery partner profit: <span className="font-mono">{fmtMoney(deliveryPartnerProfit)}</span></div><div>Suggested price: <span className="font-mono">{fmtMoney(suggestedPrice)}</span></div></div>:<p className="text-xs text-amber-800">Add at least one complete ingredient or component recipe to calculate recipe cost.</p>}</section>
  </div>;
}