import { useMemo } from "react";
import { useQuery } from "@tanstack/react-query";
import { Input } from "@/components/ui/input";
import { fmtMoney, makeIngredient, recipeIngredientCost, toNumber, type RecipeIngredientRow } from "./recipeTypes";

type PurchasingIngredient = { id:number; item:string; category?:string|null; supplierName?:string|null; brand?:string|null; supplierSku?:string|null; unitCost?:number|string|null; purchaseCostThb?:number|string|null; purchaseQuantity?:number|string|null; baseUnit?:string|null; purchaseUnitLabel?:string|null; orderUnit?:string|null; unitDescription?:string|null; active?:boolean };
type Props = { rows:RecipeIngredientRow[]; draft:RecipeIngredientRow|null; onDraftChange:(row:RecipeIngredientRow|null)=>void; onRowsChange:(rows:RecipeIngredientRow[])=>void };
const units=["g","kg","ml","L","each","pcs","pack","box","m"];

export default function RecipeIngredientEditor({rows,draft,onDraftChange,onRowsChange}:Props) {
 const {data,isLoading}=useQuery<{items?:PurchasingIngredient[]}>({queryKey:["/api/purchasing-items"],queryFn:async()=>{const r=await fetch("/api/purchasing-items?active=true");if(!r.ok)throw new Error("Could not load purchasing catalogue");return r.json();}});
 const catalogue=useMemo(()=> (data?.items??[]).filter(item=>item.active!==false),[data]);
 const beginAdd=()=>onDraftChange(makeIngredient());
 const selectIngredient=(id:string)=>{const item=catalogue.find(x=>x.id===Number(id));if(!item||!draft)return;onDraftChange({...draft,ingredientId:item.id,purchasingItemId:item.id,purchasingItemKey:String(item.id),name:item.item,sourceType:"purchasing",purchaseCost:String(item.purchaseCostThb??item.unitCost??""),packageQuantity:String(item.purchaseQuantity??""),purchaseUnit:item.baseUnit||item.orderUnit||item.unitDescription||"",unitUsed:item.baseUnit||item.orderUnit||item.unitDescription||"",wastePercent:"",autoUnitCost:null,manualOverrideUnitCost:"",costingStatus:"current_purchasing_price"});};
 const saveDraft=()=>{if(!draft||!draft.name.trim())return;const exists=rows.some(r=>r.id===draft.id);onRowsChange(exists?rows.map(r=>r.id===draft.id?draft:r):[...rows,draft]);onDraftChange(null);};
 const draftCost=draft?recipeIngredientCost(draft):{baseCost:null,wasteCost:null,lineCost:null};
 return <section className="space-y-3 rounded-lg border bg-white p-4">
  <div className="flex items-center justify-between"><div><h2 className="text-sm font-semibold">Ingredients & Costing</h2><p className="mt-1 text-xs text-slate-500">Select a purchasing ingredient to prefill its pack data, or type a manual/special-price line. Only quantity used and waste need changing for normal items.</p></div><button type="button" className="rounded-lg border px-3 py-1.5 text-xs" onClick={beginAdd}>Add Ingredient</button></div>
  {draft&&<div className="space-y-3 rounded-lg border p-3"><div className="grid grid-cols-1 gap-2 md:grid-cols-2">
   <label className="block text-xs font-medium">Purchasing ingredient<select value={draft.ingredientId??""} onChange={e=>selectIngredient(e.target.value)} className="mt-1 w-full rounded border px-2 py-2 text-xs"><option value="">{isLoading?"Loading purchasing catalogue…":"Select to prefill, or type below"}</option>{catalogue.map(i=><option key={i.id} value={i.id}>{i.item} · {fmtMoney(i.purchaseCostThb??i.unitCost)} · {i.purchaseQuantity ? `${i.purchaseQuantity} ${i.baseUnit||""}` : (i.purchaseUnitLabel||i.orderUnit||i.unitDescription||"pack details pending")}</option>)}</select></label>
   <label className="block text-xs font-medium">Ingredient name<Input value={draft.name} onChange={e=>onDraftChange({...draft,name:e.target.value,sourceType:"manual"})} className="mt-1"/></label>
   <label className="block text-xs font-medium">Purchase cost (THB)<Input type="number" min="0" step="any" value={draft.purchaseCost} onChange={e=>onDraftChange({...draft,purchaseCost:e.target.value,manualOverrideUnitCost:""})} className="mt-1"/></label>
   <label className="block text-xs font-medium">Package size / purchase quantity<Input type="number" min="0" step="any" value={draft.packageQuantity} onChange={e=>onDraftChange({...draft,packageQuantity:e.target.value})} className="mt-1"/></label>
   <label className="block text-xs font-medium">Purchase unit<select value={draft.purchaseUnit} onChange={e=>onDraftChange({...draft,purchaseUnit:e.target.value})} className="mt-1 w-full rounded border px-2 py-2 text-xs"><option value="">Select unit</option>{units.map(u=><option key={u}>{u}</option>)}</select></label>
   <label className="block text-xs font-medium">Waste %<Input type="number" min="0" max="99" step="any" placeholder="Blank = 0%" value={draft.wastePercent} onChange={e=>onDraftChange({...draft,wastePercent:e.target.value})} className="mt-1"/></label>
   <label className="block text-xs font-medium">Quantity used<Input type="number" min="0" step="any" value={draft.quantityUsed} onChange={e=>onDraftChange({...draft,quantityUsed:e.target.value})} className="mt-1"/></label>
   <label className="block text-xs font-medium">Usage unit<select value={draft.unitUsed} onChange={e=>onDraftChange({...draft,unitUsed:e.target.value})} className="mt-1 w-full rounded border px-2 py-2 text-xs"><option value="">Select unit</option>{units.map(u=><option key={u}>{u}</option>)}</select></label>
   <label className="block text-xs font-medium md:col-span-2">Notes<Input value={draft.notes} onChange={e=>onDraftChange({...draft,notes:e.target.value})} className="mt-1"/></label>
  </div><div className="flex items-center justify-between"><span className="text-xs">Base: <b>{fmtMoney(draftCost.baseCost)}</b> · Waste: <b>{fmtMoney(draftCost.wasteCost)}</b> · Line cost: <b>{fmtMoney(draftCost.lineCost)}</b></span><div className="flex gap-2"><button type="button" className="rounded-lg border px-3 py-1.5 text-xs" onClick={()=>onDraftChange(null)}>Cancel</button><button type="button" disabled={!draft.name||draftCost.lineCost===null} className="rounded-lg bg-black px-3 py-1.5 text-xs text-white disabled:opacity-40" onClick={saveDraft}>Save Ingredient</button></div></div></div>}
  <div className="overflow-x-auto rounded-lg border"><table className="w-full min-w-[1100px] text-xs"><thead><tr className="border-b bg-slate-50"><th className="p-2 text-left">Ingredient</th><th className="p-2 text-left">Purchase cost</th><th className="p-2 text-left">Package size</th><th className="p-2 text-left">Purchase unit</th><th className="p-2 text-left">Waste</th><th className="p-2 text-left">Quantity used</th><th className="p-2 text-left">Usage unit</th><th className="p-2 text-left">Line cost</th><th className="p-2 text-left">Actions</th></tr></thead><tbody>{rows.length===0?<tr><td className="p-3" colSpan={9}>No ingredients added.</td></tr>:rows.map(row=>{const cost=recipeIngredientCost(row);return <tr key={row.id} className="border-b"><td className="p-2 font-medium">{row.name}</td><td className="p-2">{fmtMoney(toNumber(row.manualOverrideUnitCost)??row.purchaseCost)}</td><td className="p-2">{row.packageQuantity||"—"}</td><td className="p-2">{row.purchaseUnit||"—"}</td><td className="p-2">{row.wastePercent||"0"}%</td><td className="p-2">{row.quantityUsed||"—"}</td><td className="p-2">{row.unitUsed||"—"}</td><td className="p-2 font-mono">{fmtMoney(cost.lineCost)}</td><td className="p-2"><button className="mr-2 underline" onClick={()=>onDraftChange(row)}>Edit</button><button className="text-red-700 underline" onClick={()=>onRowsChange(rows.filter(x=>x.id!==row.id))}>Delete</button></td></tr>})}</tbody></table></div>
 </section>;
}