import { useEffect, useMemo, useState } from "react";

const money = (value: unknown) => `฿${Number(value || 0).toLocaleString(undefined, { maximumFractionDigits: 0 })}`;

export default function AdminVenues() {
  const [venues, setVenues] = useState<any[]>([]);
  const [loading, setLoading] = useState(true);
  const [saving, setSaving] = useState(false);
  const [qr, setQr] = useState<any | null>(null);
  const [form, setForm] = useState({ name: "", contact_name: "", phone: "", address: "", notes: "" });

  const load = async () => {
    setLoading(true);
    try {
      const res = await fetch("/api/ordering/commercial/admin/venues", { credentials: "include" });
      const json = await res.json();
      if (!res.ok || !json.ok) throw new Error(json.error || "Unable to load venues");
      setVenues(json.data || []);
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => { void load(); }, []);

  const totals = useMemo(() => venues.reduce((acc, venue) => {
    acc.scans += Number(venue.qr_scans || 0);
    acc.orders += Number(venue.orders || 0);
    acc.sales += Number(venue.sales || 0);
    return acc;
  }, { scans: 0, orders: 0, sales: 0 }), [venues]);

  const createVenue = async (e: React.FormEvent) => {
    e.preventDefault();
    setSaving(true);
    try {
      const res = await fetch("/api/ordering/commercial/admin/venues", {
        method: "POST",
        credentials: "include",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify(form),
      });
      const json = await res.json();
      if (!res.ok || !json.ok) throw new Error(json.error || "Unable to create venue");
      setForm({ name: "", contact_name: "", phone: "", address: "", notes: "" });
      await load();
    } catch (error: any) {
      window.alert(error?.message || "Unable to create venue");
    } finally {
      setSaving(false);
    }
  };

  const showQr = async (venue: any) => {
    const res = await fetch(`/api/ordering/commercial/admin/venues/${venue.id}/qr`, { credentials: "include" });
    const json = await res.json();
    if (!res.ok || !json.ok) return window.alert(json.error || "Unable to load QR code");
    setQr(json.data);
  };

  const toggleVenue = async (venue: any) => {
    const res = await fetch(`/api/ordering/commercial/admin/venues/${venue.id}`, {
      method: "PATCH",
      credentials: "include",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({ is_active: !venue.is_active }),
    });
    const json = await res.json();
    if (!res.ok || !json.ok) return window.alert(json.error || "Unable to update venue");
    await load();
  };

  return (
    <div className="mx-auto max-w-7xl space-y-6 p-4 md:p-6">
      <div>
        <p className="text-sm font-semibold uppercase tracking-[0.18em] text-neutral-500">Online Ordering</p>
        <h1 className="mt-1 text-3xl font-bold text-neutral-950">Partner Venues</h1>
        <p className="mt-2 max-w-3xl text-sm text-neutral-600">Create a venue once, issue its permanent QR code, and retain clean attribution for every scan and order generated by that venue.</p>
      </div>

      <div className="grid grid-cols-1 gap-3 sm:grid-cols-3">
        {[["QR scans", totals.scans], ["Attributed orders", totals.orders], ["Attributed sales", money(totals.sales)]].map(([label, value]) => (
          <div key={String(label)} className="rounded-2xl border border-neutral-200 bg-white p-5 shadow-sm">
            <div className="text-xs font-semibold uppercase tracking-wide text-neutral-500">{label}</div>
            <div className="mt-2 text-3xl font-bold text-neutral-950">{value}</div>
          </div>
        ))}
      </div>

      <div className="grid gap-6 lg:grid-cols-[360px_1fr]">
        <form onSubmit={createVenue} className="rounded-2xl border border-neutral-200 bg-white p-5 shadow-sm">
          <h2 className="text-lg font-bold text-neutral-950">Add Partner Venue</h2>
          <p className="mt-1 text-sm text-neutral-500">The saved address becomes the locked delivery destination when this QR is scanned.</p>
          <div className="mt-5 space-y-3">
            {[
              ["Venue name", "name", true],
              ["Contact name", "contact_name", false],
              ["Phone", "phone", false],
              ["Delivery address", "address", true],
            ].map(([label, key, required]) => (
              <label key={String(key)} className="block text-sm font-medium text-neutral-700">
                {label}
                <input required={Boolean(required)} value={(form as any)[key]} onChange={(e) => setForm({ ...form, [key]: e.target.value })} className="mt-1 w-full rounded-xl border border-neutral-300 px-3 py-2.5 outline-none focus:border-neutral-950" />
              </label>
            ))}
            <label className="block text-sm font-medium text-neutral-700">Notes
              <textarea value={form.notes} onChange={(e) => setForm({ ...form, notes: e.target.value })} rows={3} className="mt-1 w-full rounded-xl border border-neutral-300 px-3 py-2.5 outline-none focus:border-neutral-950" />
            </label>
          </div>
          <button disabled={saving} className="mt-4 w-full rounded-xl bg-[#FFD400] px-4 py-3 font-bold text-black disabled:opacity-60">{saving ? "Creating…" : "Create Venue + QR"}</button>
        </form>

        <div className="overflow-hidden rounded-2xl border border-neutral-200 bg-white shadow-sm">
          <div className="border-b border-neutral-200 px-5 py-4"><h2 className="font-bold text-neutral-950">Venue Performance</h2></div>
          {loading ? <div className="p-8 text-sm text-neutral-500">Loading venues…</div> : venues.length === 0 ? <div className="p-8 text-sm text-neutral-500">No partner venues yet.</div> : (
            <div className="overflow-x-auto">
              <table className="w-full min-w-[760px] text-left text-sm">
                <thead className="bg-neutral-50 text-xs uppercase tracking-wide text-neutral-500"><tr><th className="px-5 py-3">Venue</th><th className="px-4 py-3">Scans</th><th className="px-4 py-3">Orders</th><th className="px-4 py-3">Sales</th><th className="px-4 py-3">Status</th><th className="px-4 py-3 text-right">Actions</th></tr></thead>
                <tbody className="divide-y divide-neutral-100">
                  {venues.map((venue) => <tr key={venue.id}>
                    <td className="px-5 py-4"><div className="font-semibold text-neutral-950">{venue.name}</div><div className="mt-1 text-xs text-neutral-500">{venue.address}</div></td>
                    <td className="px-4 py-4 font-semibold">{Number(venue.qr_scans || 0)}</td>
                    <td className="px-4 py-4 font-semibold">{Number(venue.orders || 0)}</td>
                    <td className="px-4 py-4 font-semibold">{money(venue.sales)}</td>
                    <td className="px-4 py-4"><span className={`rounded-full px-2.5 py-1 text-xs font-semibold ${venue.is_active ? "bg-green-100 text-green-700" : "bg-neutral-200 text-neutral-600"}`}>{venue.is_active ? "Active" : "Inactive"}</span></td>
                    <td className="px-4 py-4 text-right"><div className="flex justify-end gap-2"><button onClick={() => showQr(venue)} className="rounded-lg border border-neutral-300 px-3 py-2 text-xs font-semibold hover:bg-neutral-50">QR</button><button onClick={() => toggleVenue(venue)} className="rounded-lg border border-neutral-300 px-3 py-2 text-xs font-semibold hover:bg-neutral-50">{venue.is_active ? "Disable" : "Enable"}</button></div></td>
                  </tr>)}
                </tbody>
              </table>
            </div>
          )}
        </div>
      </div>

      {qr && <div className="fixed inset-0 z-[100] flex items-center justify-center bg-black/70 p-4" onClick={() => setQr(null)}>
        <div className="w-full max-w-md rounded-3xl bg-white p-6 text-center shadow-2xl" onClick={(e) => e.stopPropagation()}>
          <div className="text-xs font-semibold uppercase tracking-[0.18em] text-neutral-500">Partner Venue QR</div>
          <h3 className="mt-1 text-2xl font-bold text-neutral-950">{qr.name}</h3>
          <img src={qr.qr_data_url} alt={`${qr.name} ordering QR`} className="mx-auto mt-5 h-72 w-72 rounded-2xl border border-neutral-200" />
          <div className="mt-4 break-all rounded-xl bg-neutral-50 p-3 text-xs text-neutral-600">{qr.order_url}</div>
          <div className="mt-5 grid grid-cols-2 gap-2"><button onClick={() => navigator.clipboard?.writeText(qr.order_url)} className="rounded-xl border border-neutral-300 px-4 py-3 font-semibold">Copy Link</button><button onClick={() => setQr(null)} className="rounded-xl bg-neutral-950 px-4 py-3 font-semibold text-white">Done</button></div>
        </div>
      </div>}
    </div>
  );
}
