import { useEffect, useState } from "react";
import { money, patchOrderingStatus } from "@/components/ordering/orderingApi";
const statuses = ["", "SUBMITTED", "ACCEPTED", "PREPARING", "READY", "COMPLETED", "CANCELLED"];
export default function AdminOrders() {
  const [orders, setOrders] = useState<any[]>([]); const [status, setStatus] = useState(""); const [error, setError] = useState("");
  async function load() { try { const res = await fetch(`/api/ordering/admin/orders${status ? `?status=${status}` : ""}`, { credentials: "include" }); const data = await res.json(); setOrders(data.data ?? []); } catch (err:any) { setError(err.message); } }
  useEffect(() => { load(); }, [status]);
  async function confirm(orderId: string) { await fetch("/api/ordering/payments/manual-confirm", { method: "POST", credentials: "include", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ order_id: orderId, confirmed_by: "admin" }) }); load(); }
  return <main className="p-4"><h1 className="text-3xl font-bold">Ordering Orders</h1>{error && <div className="mt-4 rounded border border-red-300 bg-red-50 p-3">{error}</div>}<select className="my-4 rounded border p-2" value={status} onChange={(e) => setStatus(e.target.value)}>{statuses.map(s => <option key={s} value={s}>{s || "all"}</option>)}</select><div className="overflow-x-auto"><table className="w-full border-collapse border"><thead><tr><th className="border p-2">Order</th><th className="border p-2">Status</th><th className="border p-2">Channel</th><th className="border p-2">Items</th><th className="border p-2">Total</th><th className="border p-2">Actions</th></tr></thead><tbody>{orders.map(o => <tr key={o.id}><td className="border p-2">#{o.order_number}</td><td className="border p-2">{o.status_code ?? o.status}<br />{o.payment_status}</td><td className="border p-2">{o.channel}{o.table_code ? ` / ${o.table_code}` : ""}</td><td className="border p-2">{o.items?.map((i:any)=><div key={i.id}>{i.quantity} × {i.item_name_en}</div>)}</td><td className="border p-2">{money(o.total)}</td><td className="border p-2"><button className="mr-2 rounded border px-2 py-1" onClick={() => confirm(o.id)}>Confirm payment</button><button className="rounded border px-2 py-1" onClick={async () => { await patchOrderingStatus(o.id, "CANCELLED", "admin"); load(); }}>Cancel</button></td></tr>)}</tbody></table></div></main>;
}
